### ISSUE TITLE
Eror

### ISSUE THREAD

**Issue by YaNIND** [KingOfTurkey38/Vaults38#3]
![IMG_20220311_231904](https://user-images.githubusercontent.com/84168756/157906319-fec04dcc-e8d1-41fc-b0fc-c16d5e23af6b.jpg)

**Comment by KingOfTurkey38** [comment]
Your MySQL credentials are not correct in the config.yml file

**Comment by YaNIND** [comment]
does it only support mysql unlike yml?

**Comment by YaNIND** [comment]
![IMG_20220312_010938](https://user-images.githubusercontent.com/84168756/157925412-d6c772ce-c1b3-476a-9eed-9de2ab0f1ee3.jpg)

**Comment by YaNIND** [comment]
@KingOfTurkey38

**Comment by KingOfTurkey38** [comment]
This plugin only supports MySQL

**Comment by YaNIND** [comment]
> This plugin only supports MySQL

why pls ad sqlite supports

**Comment by KingOfTurkey38** [comment]
I have no plans on adding SQLite support. Feel free to create a PR for it.
